"""empty message

Revision ID: d485caf99782
Revises: 47385c7f7477
Create Date: 2024-08-29 21:36:50.481516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd485caf99782'
down_revision = '47385c7f7477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frequently_ask', sa.String(length=100), nullable=False),
    sa.Column('relaxation_exercises', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('frequently_ask'),
    sa.UniqueConstraint('relaxation_exercises')
    )
    op.create_table('manager',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('lastname'),
    sa.UniqueConstraint('name')
    )
    op.create_table('psychologist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lastname', sa.String(length=100), nullable=False),
    sa.Column('experience', sa.String(length=100), nullable=False),
    sa.Column('language', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('experience'),
    sa.UniqueConstraint('language'),
    sa.UniqueConstraint('lastname'),
    sa.UniqueConstraint('name')
    )
    op.create_table('calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=100), nullable=False),
    sa.Column('month', sa.String(length=100), nullable=False),
    sa.Column('hour', sa.String(length=120), nullable=False),
    sa.Column('userCalendar', sa.Integer(), nullable=False),
    sa.Column('psychologistCalendar', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['psychologistCalendar'], ['psychologist.id'], ),
    sa.ForeignKeyConstraint(['userCalendar'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day'),
    sa.UniqueConstraint('hour'),
    sa.UniqueConstraint('month')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('introductory', sa.Integer(), nullable=False),
    sa.Column('fullSession', sa.Integer(), nullable=False),
    sa.Column('sessionPackage_5', sa.Integer(), nullable=False),
    sa.Column('sessionPackage_10', sa.Integer(), nullable=False),
    sa.Column('usersession', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['usersession'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fullSession'),
    sa.UniqueConstraint('introductory'),
    sa.UniqueConstraint('sessionPackage_10'),
    sa.UniqueConstraint('sessionPackage_5')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('lastname', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('age', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('gender', sa.String(length=80), nullable=False))
        batch_op.create_unique_constraint(None, ['gender'])
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.create_unique_constraint(None, ['lastname'])
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('gender')
        batch_op.drop_column('age')
        batch_op.drop_column('lastname')
        batch_op.drop_column('name')

    op.drop_table('session')
    op.drop_table('calendar')
    op.drop_table('psychologist')
    op.drop_table('manager')
    op.drop_table('chatbot')
    # ### end Alembic commands ###
