"""empty message

Revision ID: f71f1a071137
Revises: 404a856d234d
Create Date: 2024-09-09 09:32:21.381401

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f71f1a071137'
down_revision = '404a856d234d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_call', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_session', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('session_package_5', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('session_package_10', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('session_call_sessionPackage_10_key', type_='unique')
        batch_op.drop_constraint('session_call_sessionPackage_5_key', type_='unique')
        batch_op.drop_constraint('session_call_user_session_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.drop_column('user_session')
        batch_op.drop_column('sessionPackage_10')
        batch_op.drop_column('fullSession')
        batch_op.drop_column('sessionPackage_5')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_call', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sessionPackage_5', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fullSession', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sessionPackage_10', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('user_session', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('session_call_user_session_fkey', 'user', ['user_session'], ['id'])
        batch_op.create_unique_constraint('session_call_sessionPackage_5_key', ['sessionPackage_5'])
        batch_op.create_unique_constraint('session_call_sessionPackage_10_key', ['sessionPackage_10'])
        batch_op.drop_column('user_id')
        batch_op.drop_column('session_package_10')
        batch_op.drop_column('session_package_5')
        batch_op.drop_column('full_session')

    # ### end Alembic commands ###
